name: Push changed files to SGr server
run-name: ${{ github.actor }} is pushing changed files to SGr server ðŸš€
on:
  push:
    branches:
      - 'master'
jobs:
  upload:
    runs-on: ubuntu-latest
    name: Push uploaded files to SGr server
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Get changed files
      uses: tj-actions/changed-files@v35
      with:
        # include_all_old_new_renamed_files: true
        fetch_depth: 1
      id: changed-files
      
    - name: push changed files via curl to SGrWebApp
      env:
        SGR_WEB_APP_TOKEN: ${{ secrets.SGR_WEB_APP_TOKEN }}
        ALL_CHANGED_AND_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
        ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
        DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        RENAMED_FILES: ${{ steps.changed-files.outputs.renamed_files }}
      run: |
        for file in "$ALL_CHANGED_AND_MODIFIED_FILES"; do # detects deleted files, too
          echo "detected changed file: $file"
        done
        for file in "$ADDED_FILES"; do
          echo "try to upload added file: $file"
          curl --silent --upload-file "$file" "https://library.smartgridready.ch/$file?add&token=$SGR_WEB_APP_TOKEN"
        done
        for file in "$MODIFIED_FILES"; do
          echo "try to upload modified file: $file"
          curl --silent --upload-file "$file" "https://library.smartgridready.ch/$file?update&token=$SGR_WEB_APP_TOKEN"
        done
        for file in "$DELETED_FILES"; do
          echo "try to delete file: $file"
          curl --silent "$file" "https://library.smartgridready.ch/$file?delete&token=$SGR_WEB_APP_TOKEN"
        done
        for file in "$RENAMED_FILES"; do
          echo "try to upload renamed file: $file (as update as we do not know the old name)"
          curl --silent --upload-file "$file" "https://library.smartgridready.ch/$file?update&token=$SGR_WEB_APP_TOKEN"
        done
